### ISSUE TITLE
Bug in HCm-Teff_v5.2.py

### ISSUE THREAD

**Issue by nimishak-cosmos** [Borja-Perez-Diaz/HII-CHI-Mistry#1]
Hi, 

There appears to be a bug in lines 564 and 572  of the code Him-Teff_v5.2.py. 

Currently, line 564 is:

SIII_9069 = input1['SIII_9069']/2.44

I think it should be:

SIII_9069 = input1['SIII_9532']/2.44

Similarly, line 572 is:

eSIII_9069 = input1['eSIII_9069']/2.44

and it should be:

eSIII_9069 = input1['eSIII_9532']/2.44

Best Regards,
Nimisha

**Comment by Borja-Perez-Diaz** [comment]
Hi Nimisha,

Thank you for reporting the bug. It is fixed now in all versions, as well as in our new update for the code (HCm-Teff_v5.3) which now accounts for [NII] emission lines that can replace [SII], more affected by background diffuse ionized gas.

Best regards,
Borja Pérez-Díaz
